###################################################################################################
# Recyclarr Configuration Template: HD Bluray + WEB (GER)                                         #
# Updated: 2025-05-04                                                                             #
# Documentation: https://recyclarr.dev                                                            #
# Note: If you are using multiple profiles in a single instance, please read the following        #
# documentation about file merging:                                                               #
# https://recyclarr.dev/wiki/yaml/config-examples/#merge-single-instance                          #
###################################################################################################
# Instance Definition: https://recyclarr.dev/wiki/yaml/config-reference/basic/

#localCustomFormatsPath: /opt/configarr-configs/cfs
#localConfigTemplatesPath: /app/templates

# true or false
sonarrEnabled: false
radarrEnabled: true
whisparrEnabled: false
readarrEnabled: false
lidarrEnabled: false

### <<< Define new custom formats >>>
customFormatDefinitions:
  - trash_id: custom-allow-fun-microsized
    trash_scores:
      default: 34950
    trash_description: "Microsized: Allow FuN"
    name: "Microsized: Allow FuN"
    includeCustomFormatWhenRenaming: false
    specifications:
      - name: Allow FuN microsized
        implementation: ReleaseGroupSpecification
        negate: false
        required: false
        fields:
          value: "^(FuN)$"

  - trash_id: max-10gb-bonus
    trash_scores:
      default: 500
    trash_description: "10GB Bonus"
    name: "10GB Bonus"
    includeCustomFormatWhenRenaming: false
    specifications:
     - name: max10GB
       implementation: SizeSpecification
       negate: false
       required: true
       fields:
         min: 7
         max: 10
     - name: 1080p
       implementation: ResolutionSpecification
       negate: false
       required: true
       fields:
         value: 1080

  - trash_id: max-7gb-bonus
    trash_scores:
      default: 600
    trash_description: "7GB Bonus"
    name: "7GB Bonus"
    includeCustomFormatWhenRenaming: false
    specifications:
     - name: max7GB
       implementation: SizeSpecification
       negate: false
       required: true
       fields:
         min: 3
         max: 7
     - name: 1080p
       implementation: ResolutionSpecification
       negate: false
       required: true
       fields:
         value: 1080

  - trash_id: above-12gb
    trash_scores:
      default: -500
    trash_description: "Max. 12GB"
    name: "Max. 12GB"
    includeCustomFormatWhenRenaming: false
    specifications:
     - name: max12GB
       implementation: SizeSpecification
       negate: true
       required: true
       fields:
         min: 0
         max: 12

  - trash_id: above-20gb
    trash_scores:
      default: -3000
    trash_description: "Max. 20GB"
    name: "Max. 20GB"
    includeCustomFormatWhenRenaming: false
    specifications:
     - name: max20GB
       implementation: SizeSpecification
       negate: true
       required: true
       fields:
         min: 0
         max: 20

  - trash_id: max8gb-for-older-movies-1990
    trash_scores:
      default: -2900
    trash_description: "Year 1990 small size"
    name: "Sizelimit till 1990"
    includeCustomFormatWhenRenaming: false
    specifications:
    - name: max8GB
      implementation: SizeSpecification
      negate: true
      required: true
      fields:
        min: 0
        max: 8
    - name: Before1990
      implementation: YearSpecification
      negate: false
      required: true
      fields:
        min: 1800
        max: 1990
### <<< End new custom formats >>>

radarr:
  hd-bluray-web-ger:
    base_url: http://192.168.2.170:7878/
    api_key: !secret RADARR_API_KEY # Reference to API key in secrets.yml
    # media_management:
    #   id: 1
    #   autoUnmonitorPreviouslyDownloadedMovies: false
    #   recycleBinCleanupDays: 3
    #   downloadPropersAndRepacks: doNotPrefer
    #   createEmptyMovieFolders: false
    #   deleteEmptyFolders: false
    #   fileDate: "none"
    #   rescanAfterRefresh: always
    #   autoRenameFolders: true
    #   pathsDefaultStatic: true
    #   setPermissionsLinux: false
    #   chmodFolder: ""
    #   chownGroup: ""
    #   skipFreeSpaceCheckWhenImporting: false
    #   minimumFreeSpaceWhenImporting: 50000
    #   copyUsingHardlinks: true
    #   useScriptImport: false
    #   importExtraFiles: true
    #   extraFileExtensions: .srt, .sub, .idx, .vob, .nfo, .stl, .sup, .vtt, .info
    #   enableMediaInfo: true
    # media_naming_api:
    #   id: 1
    #   renameMovies: true
    #   replaceIllegalCharacters: true
    #   colonReplacementFormat: delete
    #   standardMovieFormat: "{Movie Title:DE}{(Release Year)} [tmdb-{TmdbId}] -
    #     {Edition Tags }{[Custom Formats]}{[Quality Full]}{[MediaInfo 3D]}{[MediaInfo
    #     VideoDynamicRangeType]}{[Mediainfo AudioCodec}{ Mediainfo
    #     AudioChannels]}{[Mediainfo VideoCodec]}{-Release Group}"
    #     {Movie CleanTitle} {(Release Year)} {tmdb-{TmdbId}} 
    #     {edition-{Edition Tags}} {[Custom Formats]}{[Quality Full]}{[MediaInfo 3D]}{[MediaInfo 
    #     VideoDynamicRangeType]}{[Mediainfo AudioCodec}{ Mediainfo 
    #     AudioChannels]}{[Mediainfo VideoCodec]}{-Release Group}
    #   movieFolderFormat: "{Movie Title:DE} ({Release Year}) {tmdb-{TmdbId}}"


    cloneQualityProfiles:
      - from: "HD Bluray + WEB (GER)"
        to: "HD Highest"
      - from: "HD Bluray + WEB (GER)"
        to: "HD Standard"
      - from: "HD Bluray + WEB (GER)"
        to: "HD Small"
      - from: "HD Bluray + WEB (GER)"
        to: "HD FuN"

    include:
#      - template: radarr-quality-definition-movie
      - template: radarr-custom-formats-hd-bluray-web-german
      - template: radarr-quality-profile-hd-bluray-web-german

    quality_profiles:
      - name: HD Highest
        min_format_score: 9000 # Uncomment this line to skip English Releases
      - name: HD Standard
        min_format_score: 9000 # Uncomment this line to skip English Releases
      - name: HD Small
        min_format_score: 7000 # Uncomment this line to skip English Releases
      - name: HD FuN
        min_format_score: 7000 # Uncomment this line to skip English Releases

    custom_formats:
### Optional
      - trash_ids:
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
#          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
#          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
#          - f537cf427b64c38c8e36298f657e4828 # Scene
          - 182fa1c42a2468f8488e6dcf75a81b81 # Internal +10
        assign_scores_to:
          - name: HD Highest
          - name: HD Standard
          - name: HD Small
          - name: HD FuN

      - trash_ids:
### Movie Versions - Uncomment any of the following lines to prefer these movie versions
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
#          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
#          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
#          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        assign_scores_to:
          - name: HD Highest
          - name: HD Standard
          - name: HD Small
          - name: HD FuN

### Prefer good x265 releases e.g. VECTOR 
      - trash_ids:
         - dc98083864ea246d05a42df0d05f81cc # Prefer good x265 releases e.g. VECTOR
        assign_scores_to:
          - name: HD Standard
            score: 300
          - name: HD Small
            score: 1500
          - name: HD FuN
            score: 2000
### reduce 720p score
      - trash_ids:
          - b2be17d608fc88818940cd1833b0b24c
        assign_scores_to:
          - name: HD Standard
          - name: HD Small
          - name: HD FuN
            score: -1105
### reduce old movie score
      - trash_ids:
         - max8gb-for-older-movies-1990
        assign_scores_to:
          - name: HD Standard
          - name: HD Small
          - name: HD FuN
### allow / prefer FuN
      - trash_ids:
          - custom-allow-fun-microsized
        assign_scores_to:
          - name: HD Standard
          - name: HD Small
            score: 36650
          - name: HD FuN
            score: 39000
### give smaller files a bonus 10gb
      - trash_ids:
          - max-10gb-bonus
        assign_scores_to:
          - name: HD Standard
      - trash_ids:
          - max-10gb-bonus
        assign_scores_to:
          - name: HD Standard
          - name: HD Small
            score: 900
### give smaller files a bonus 7gb
      - trash_ids:
          - max-7gb-bonus
        assign_scores_to:
          - name: HD Standard
      - trash_ids:
          - max-7gb-bonus
        assign_scores_to:
          - name: HD Standard
          - name: HD Small
            score: 1000
### punish bigger files 12gb
      - trash_ids:
          - above-12gb
        assign_scores_to:
          - name: HD Standard
          - name: HD Small
            score: -1000
### reduce and "flatten" German HQ Release Groups - all good enough
      - trash_ids:
          - 54795711b78ea87e56127928c423689b # German Bluray Tier 01
          - 1bfc773c53283d47c68e535811da30b7 # German Bluray Tier 02
          - aee01d40cd1bf4bcded81ee62f0f3659 # German Bluray Tier 03
          - a2ab25194f463f057a5559c03c84a3df # German Web Tier 01
          - 08d120d5a003ec4954b5b255c0691d79 # German Web Tier 02
          - 439f9d71becaed589058ec949e037ff3 # German Web Tier 03
          - 2d136d4e33082fe573d06b1f237c40dd # German Scene
        assign_scores_to:
          - name: HD Small
            score: 1600
          - name: HD FuN
            score: 1000
 ### reduce HQ Release Groups
      - trash_ids:
          - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
          - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
          - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
        assign_scores_to:
          - name: HD Small
            score: 600
          - name: HD FuN
            score: 0




### x265 - IMPORTANT: Only use on of the options below.
#       - trash_ids:
# #          - 839bea857ed2c0a8e084f3cbdbd65ecb # Uncomment this line to allow HDR/DV x265 HD releases
#         assign_scores_to:
#           - name: HD Highest

#       - trash_ids:
# #          - dc98083864ea246d05a42df0d05f81cc # Uncomment this line to block all x265 HD releases
#         assign_scores_to:
#           - name: HD Highest
#             score: -35000

### Generated Dynamic HDR
#       - trash_ids:
# #          - e6886871085226c3da1830830146846c # Uncomment this line to block Generated Dynamic HDR
#         assign_scores_to:
#           - name: HD Highest
#             score: -35000

### x265 allow German microsized (FuN)
#      - trash_ids:
#          - 03c430f326f10a27a9739b8bc83c30e4 
#        assign_scores_to:
#          - name: HD Highest
#            score: 0